### ISSUE TITLE
Zoom level is not preserved when switching to another message

### ISSUE THREAD

**Issue by parrenin** [thunderbird-conversations/thunderbird-conversations#1273]
* **Thunderbird version:**
52.7
* **Thunderbird Conversation version:**
2.13.4
* **Operating System:**
Linux

**What did you do?**
- go to a message
- increase zoom level by doing 3 times CTRL+
- then go to another message
**What did you expect to happen?**
zoom level should be preserved
**What actually happened?**
zoom level is not preserved.
But if you zoom again with one CTRL+, the 3 previous CTRL+ are applied

**Comment by Standard8** [comment]
In the latest version just released (3.1.2), the Zoom level is now preserved selecting messages within a folder. It still isn't preserved going across different folders.

It does respect the size settings under font & colours in the display/formatting section of the preferences.

**Comment by Standard8** [comment]
Hmm, I suspect my previous comment was tested on Thunderbird 68. Testing on Thunderbird 78, Zoom levels are preserved across messages and folders. Hence closing this out as fixed.

The message itself is still not zoomed properly - we have #1600 on file for that which should hopefully be fixed in Thunderbird 91.
