### ISSUE TITLE
Standard 12 Hour Time Needed

### ISSUE THREAD

**Issue by sileeb** [thunderbird-conversations/thunderbird-conversations#1556]
Hi there.. I got 2 questions...

1) Would appreciate it if you would transform the military time to standard 12 hour time on emails. It would be much easier to understand the time for many of us. Check out the screen shot:

![22](https://user-images.githubusercontent.com/73712645/99106202-dea92c00-25b1-11eb-9e42-18b6f1a56354.png)

2) When will quick reply be fixed?

Appreciate your time and efforts.

**Comment by Standard8** [comment]
Hi, the date shown in that list is directly from the header in the email message. We show those headers without changes so that the original headers can be easily examined.

The date/time at the top-right should be in the format of the rest of the system.

For quick reply, I have a prototype but it needs quite a bit more work before it'll be ready as a basic replacement. Follow #1361 and #1513 for the latest status, and what needs doing if you or anyone else want to help out.

**Comment by sileeb** [comment]
Is there any way of changing or modifying it to show the time in regular standard 12 hour format? Is there something you could suggest that I may try to tweak the code on my end to show the desired time format?
