### ISSUE TITLE
messageDisplay.onMessageDisplayed is broken with Conversations installed

### ISSUE THREAD

**Issue by mlazdans** [thunderbird-conversations/thunderbird-conversations#1562]
After installing your add-on TB official messageDisplay API is no longer working for other add-ons, for example:

messageDisplay.onMessageDisplayed.addListener(async (Tab, Message) => {
}

Now Message comes in null.

**Comment by Standard8** [comment]
Thanks for the report, Conversations does do various things to the message display routines, so I'm not totally surprised, I'll see if I can track down what's happening.

**Comment by Standard8** [comment]
Interesting, `messageDisplay.onMessagesDisplayed` works (with selections across multiple threads), but `messageDisplay.onMessageDisplayed` doesn't (single message or thread, or messages in a thread), same with the equivalent `messageDisplay.getDisplayedMessage` function.

I think it is because of the way Conversations effectively enforces displaying multi-message display all the time (but some parts still see it as a single-selection).

I'll have to probe deeper.

**Comment by Standard8** [comment]
I've now worked it out, due to the way Conversations was replacing things, it needed to handle firing those off manually. This should be working for both `onMessageDisplayed` and `onMessagesDisplayed` with the latest master I've just pushed.

Note that `onMessagesDisplayed` might be more accurate for when threads are selected (it got added recently).

I'm hopefully going to cut a new release in the next day or two, there's one other thing I definitely want to sort out first.

**Comment by mlazdans** [comment]
Thanks for fixing it.

As you modify TB internals I was wondering if it is possible for your add-on to invoke browser.messageDisplay.onMessageDisplayed() when user opens any message under conversations?

I'm asking because now if user kinda opens message but official API is not getting called. I think it should be called? What's your thoughts?

**Comment by Standard8** [comment]
The problem is how you define "opened". If a thread of messages are unread and you select them then it'll open multiple messages, alternately a user can expand and collapse individual messages.

We could possibly dispatch `onMessagesDisplayed` in this case - though at some stage, Conversations is trying to move away from the experimental APIs to use the WebExtension APIs, so that would stop working again.

I think a lot of it would really depend on the objectives of other add-ons.

**Comment by mlazdans** [comment]
By opened I mean when user explicitly expand a single message. For example if any add-on's functionality relies on (official TB API?) [onMessagesDisplayed](https://thunderbird-webextensions.readthedocs.io/en/78/messageDisplay.html#onmessagedisplayed-tab-message) (or onMessagesDisplayed - haven't checked if this still gets called though) event (e.g. user clicks on message) it is now a broken add-on when used together with Conversations.

If you move to only using WebExtension APIs that this should not be a problem I guess? I'm not sure if Conversations functionality could be implemented using only existing at the moment WebExtension APIs...

**Comment by Standard8** [comment]
> By opened I mean when user explicitly expand a single message. For example if any add-on's functionality relies on (official TB API?) [onMessagesDisplayed](https://thunderbird-webextensions.readthedocs.io/en/78/messageDisplay.html#onmessagedisplayed-tab-message) (or onMessagesDisplayed - haven't checked if this still gets called though) event (e.g. user clicks on message) it is now a broken add-on when used together with Conversations.

I think this very much depends on what the add-on needs it for. The user might expand a message, but they may then go onto looking at a totally different message. So if anything, you could even want to know about which message is in the viewport, but again, that depends on what the add-on needs it for.

> If you move to only using WebExtension APIs that this should not be a problem I guess? I'm not sure if Conversations functionality could be implemented using only existing at the moment WebExtension APIs...

It can't at the moment, this is something that we're working towards, so we have to keep that in mind as well.

**Comment by mlazdans** [comment]
> The user might expand a message, but they may then go onto looking at a totally different message.

Yes user might but the event should fire when a message **is** displayed, so it should be irrelevant if the user "looks" at different messages in the thread after display?

I'm playing around with Conversations a bit more while I'm writing here and while messageDisplay.onMessageDisplayed call with _null_ is fixed now, this event is actually also fired when user expands message in Conversation thread (this actually is what I've been asking for you to implement so Conversations do not break official API).

However, event's Message parameter comes in with the data from message that is selected in message pane not the actual expanded message from the thread below it. And it is fired only once - when the message in the thread is expanded for the first time. When further collapse/expand is done no events are fired. Not sure who is firing it though - TB or Conversations.

Because Conversations pretty much override standart behavior I believe messageDisplay.onMessageDisplayed should still be fired with the message data of what is expanded (i.e. displayed) and not the message data from "upper" message. Otherwise it feels that official API is kinda broken now. Any thoughts?
