### ISSUE TITLE
Deleting a thread causes messages to open in browser.

### ISSUE THREAD

**Issue by Althejazzman** [thunderbird-conversations/thunderbird-conversations#1604]
I hope the cross-linking is acceptable, but I've already described this and posted screenshots on Bugzilla:
[https://bugzilla.mozilla.org/show_bug.cgi?id=1683634](url)

 Today I have determined that Thunderbird-Conversations is the culprit so I thought it best to report the problem here.

The other add-ons I use are:
- Provider to CalDAV & CardDAV
- Quicktext
- TBSync

**Comment by Standard8** [comment]
Unfortunately I have no idea how Conversations would cause this to happen, nor have I heard of it before. When deleting a message Conversations will tell Thunderbird to remove it, then load the next one. It does not attempt to load messages in browser windows, nor does it attempt to save temporary files which could be opened.

Additionally using the delete key is probably kicking in Thunderbird's deletion mechanism directly.

My only thought would be to check your preferences in the "General" section specifically the "Files & Attachments" part. Maybe something there has been set wrongly.

**Comment by Standard8** [comment]
I've no idea why that would be then. Unless Chrome is randomly deciding to open temporary files for some reason, but even then, I don't know how Conversations would be causing those to be created.

**Comment by Standard8** [comment]
Unfortunately I still have no idea what could be causing this. My best guess would be to try in a [fresh profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-thunderbird-profiles) and see if that helps.

This feels like there's some sort of setting somewhere that's causing Chrome to open temporary files for some weird reason. The temp file referenced in the screenshot in the bug is of a temporary file that Thunderbird would have created - the add-on itself does not create anything.

With the fresh profile, my thought would be eliminating anything that's changed expectedly or unexpectedly.

I'm closing this for now as I have no better ideas, and I've never heard of it affecting anyone else. If there's some more details about how to reproduce, I'll be happy to make more suggestions.
