### ISSUE TITLE
Thunderbird freezes when clicking on the "notification of new Email windows overlay"

### ISSUE THREAD

**Issue by Johneltonsbrain** [thunderbird-conversations/thunderbird-conversations#1630]
* **Thunderbird version: 78.10.0**
* **Thunderbird Conversation version: 3.2.17**
* **Operating System: Windows 10**

**What did you do? Click on the notification overlay bottom right**

**What did you expect to happen? Thunderbird showing the Email**

**What actually happened? Thunderbird froze and gave me the option to close the software**

This issue appeared after installing the conversation extension.

**Comment by Standard8** [comment]
How long does it freeze for? Have you tried waiting for a few minutes?

Also, have you tried manually selecting the messages that have come in the message list, rather than clicking the notification?

I'd suggest also to try and get a [profile of the freeze](https://github.com/thunderbird-conversations/thunderbird-conversations/wiki/Profiling-Conversation's-Performance) - that might reveal something going on in the background.

**Comment by Standard8** [comment]
Unfortunately with no further information I'm unable to progress this further.
