### ISSUE TITLE
Not honored: mail.ShowCondensedAddresses

### ISSUE THREAD

**Issue by murty2** [thunderbird-conversations/thunderbird-conversations#1664]
Not honored: mail.ShowCondensedAddresses

Please resist the urge to patronize and use friendly headers. Such as:
```
From: Me <...>
To: The Other person <..>
Date: Not today
```
These may be helpful to children but otherwise pretty useless to everyone else.
I want to see the real headers, not something that wants to outsmart me.

**Comment by Standard8** [comment]
Please use the provided template when reporting issues. It is there to make it easier for developers to understand the issue and ensure we have good information rather than having to guess or ask questions.

> Please resist the urge to patronize and use friendly headers.

We are not patronizing people, we are making it simpler to understand at a glance. This is something that is personal preference, of course, but we are not being patronizing.

> From: Me <...>
> To: The Other person <..>

Please explain exactly what is not working here. `mail.showCondensedAddresses` determines if the email address is shown for contacts which are in your address book / your identity.

If there is a contact in your address book, and `mail.showCondensedAddresses` is true, then the contact will be shown as simply a name. Otherwise it will be shown as a name and email.

> Date: Not today

Again, you've not explained this well, but I'm going to assume you mean that you don't like the dates system. If so, you can go into Tools -> Add-ons, select the spanner symbol next to Conversations, and then tick the "No friendly dates". It will take effect when you next change message threads.

**Comment by Standard8** [comment]
I'm sorry, without further details I'm unable to help, hence closing this out.
