### ISSUE TITLE
Threading in Thunderbird Mac is not working

### ISSUE THREAD

**Issue by WinstonBarns** [thunderbird-conversations/thunderbird-conversations#1775]
Is there a way to make SORTING BY THREAD and EXPANDING ALL THREADS a DEFAULT?
Sometimes, "SORTING THREAD" survives re-starts.
"EXPANDING ALL THREADS" never survives a re-start. And, most of the time, it gets disabled in mid-session.
Thanks for your help.

**Comment by Standard8** [comment]
Please don't use capitals. It isn't necessary and feels like your shouting.

Conversations only sets the default sort order and expansion preferences on first install when the assistant is run and if selected. It is not touching them at other times.

This may help you: In Preferences -> General there is a "Config Editor" button near the bottom of it. Acknowledge the warning, and then search for `mailnews.default_view_flags`. It will likely be `1`.

Try clicking the undo button at the right, so that it is `0` and then restarting. You may also need to re-apply settings to each folder.

If that doesn't work then I don't think this is an issue with Conversations itself, please try asking at http://support.mozilla.org/thunderbird/

**Comment by Standard8** [comment]
Oh, and to clarify something: If changing it via the menus doesn't save across restarts, but changing the preference does, then I think there may still be a Thunderbird issue in there - that's up to Thunderbird itself to be saving those views.

**Comment by WinstonBarns** [comment]
Sorry to have offended your critically sensitive "ears".
That sort of sophomoric stuff left us likely well  prior to your first email.
