### ISSUE TITLE
Slow preview of attached images

### ISSUE THREAD

**Issue by mmorandi** [thunderbird-conversations/thunderbird-conversations#1785]
* 91.5.1 (64-bit)
* 4.0.11
* Linux, OpneSuSE Tumbleweed

Click on an email with attached a relatively big .ipeg picture attached (6.2 MB)

Thunderbird becomes irresponsible for some time while the preview of the image is (very slowly) being generated at the bottom left of the email, under the list of attachments

If this is not fixable, it could be useful to have an option to turn off the generation of the preview.

I've uploaded the recorded profile at https://share.firefox.dev/3LmIWjR
At some point the recording buffer was full; at that point I stopped the profile recording.

**Comment by Thoniur** [comment]
I'm experiencing the same behavior for some time on W11 64-bit, version 21H2.

The size of the attached images is usually <3 MB.
The mem usage in the Task Manager increases rapidly while the mail is opened.

**Comment by vicharak119** [comment]
Hi Jonathan,

First Of All Thank you for such a nice add on. It really saves lot of our time..

I am also facing similar issue (described below)..

Since Last few TB updates I have noticed that if email has a large image attachment, it take log time to load / open email.. Large means sometime 20-30 mins also.. Many a time it needs to be restarted.. 

Till the time it loads completely or we restart TB, we can not do any thing..

It will be great if you can assist if we are doing something wrong or we can do something for it..

Need your help to resolve this issues.

**Comment by Standard8** [comment]
I took a look at this earlier. I've improved a bit how the gallery loads with large images (the page you get to when you click one of the images), however for the images in messages I still need to rework that - unfortunately it is going to be easier to do once I finish a re-architecture I'm working on for message loading. Hopefully I can finish that soon, and then sort this out as well.

**Comment by Standard8** [comment]
I think I've now improved things a bit, the loading of the image shouldn't happen until after the initial render. Whilst it might be a bit slow whilst loading, there isn't too much more I can do about this at the moment. Maybe in future we'll hopefully be able to handle this better across separate processes.
