### ISSUE TITLE
View using classic reader

### ISSUE THREAD

**Issue by amourchaleur** [thunderbird-conversations/thunderbird-conversations#1812]
Hi! I am on the latest version and would like to check if it is possible that when I double click on an email message, it opens up a new tab  (same as when I click on view using classic reader)? 

Currently when I double click on an email message, it opens a pop up instead. It doesn't show the full subject, recipients and other options available when I use view using classic reader.

I actually need the email subject and recipients to show up in full in the conversation preview, but since it doesn't, I will need to view using classic reader to do that.

Appreciate any advise.

Thank you.

**Comment by Standard8** [comment]
> Hi! I am on the latest version and would like to check if it is possible that when I double click on an email message, it opens up a new tab (same as when I click on view using classic reader)?
> 
> Currently when I double click on an email message, it opens a pop up instead.

Conversations follows the same setting as you have for Thunderbird. In the General preferences dig around under Reading & Display and the "Open messages in" preference.

> It doesn't show the full subject, recipients and other options available when I use view using classic reader.
> 
> I actually need the email subject and recipients to show up in full in the conversation preview, but since it doesn't, I will need to view using classic reader to do that.

It is unclear what you mean by this, since Conversations always displays all recipients and the full subject, but it is limited by the display width, so maybe that's what you mean?

If that's the case, go into the General preferences and at the bottom there's a Config Editor button. Go into that and acknowledge the warning then search for `mail.show_headers`. Double click the value (probably the default of 1) and set that to 2. That will cause Conversations to display all the message headers vertically whenever you open a new message.

**Comment by Standard8** [comment]
I'm assuming my previous comment resolved the issues so closing this out.
