### ISSUE TITLE
Sent items not included in TC when texting on Desktop/Thunderbird and Mobile/Gmail App

### ISSUE THREAD

**Issue by Sick-Andrew** [thunderbird-conversations/thunderbird-conversations#1861]
* **Thunderbird version:** 91.10.0
* **Thunderbird Conversation version:** 4.0.19
* **Operating System:** Win 10

**What did you do?**
Sent an e-mail from Android Gmail app as a reply to an existing conversation.

**What did you expect to happen?**
Thunderbird Conversation should have included that reply into the conversation when on the desktop version.

**What actually happened?**
The mail inbox is the same on Win 10 and Android. The sent e-mail is shown in the "sent" folder on Thunderbird PC and Gmail app - so the folders (e.g. "sent") and the account are correctly set up on both devices. But my message does not show up in the Thunderbird Conversation view as a reply. Funnily, when the recipience has received my reply and replies back to it, the new email is shown in the Thunderbird Conversation - just without my message that I sent from the phone before.

**Comment by Standard8** [comment]
For a conversation to show up in Thunderbird it would require the folder to be both synced and indexed. This may not happen in normal use - Thunderbird does not always check all folders for new emails.

If you've visited the sent folder and the email has downloaded, then there is also an indexing stage that needs to happen. This normally happens if Thunderbird is left idle in the background for a few minutes.

After that stage the email should show up.

If it doesn't, then on one of the messages, hover over the person you are communicating with and select the "Recent Conversations" button. Do the messages listed there in the top section show correctly as threaded? If not, then this is an issue with message threading - which may be caused by the Android Gmail app breaking the threads.

Otherwise, I suspect it would be Thunderbird not always retrieving and indexing the mesages which is causing this problem. You may want to turn on checking the folder for new mail (via right-click properties), as that would force Thunderbird to regularly check that folder for additions.

**Comment by Sick-Andrew** [comment]
> For a conversation to show up in Thunderbird it would require the folder to be both synced and indexed. This may not happen in normal use - Thunderbird does not always check all folders for new emails.
> 
> If you've visited the sent folder and the email has downloaded, then there is also an indexing stage that needs to happen. This normally happens if Thunderbird is left idle in the background for a few minutes.
> 
> After that stage the email should show up.


**So far so good. The messages show up in the sent folder. I just checked with a conversation from about a week ago. Thunderbird runs daily for several hours on that computer.**


> If it doesn't, then on one of the messages, hover over the person you are communicating with and select the "Recent Conversations" button. Do the messages listed there in the top section show correctly as threaded? If not, then this is an issue with message threading - which may be caused by the Android Gmail app breaking the threads.

**Now here is the thing: The messages show up in sent. But they are not assigned to the conversation. If I try clicking at the "Recent Conversations" button as you suggested, nothing happens next. I do see see the tooltip of the button when hovering, though. The other buttons such as "send email" or "edit contact" do work.**

**Here is an example of what I see in my sent folder when TB/TC and Gmail app engage in the same conversation:**

![conversations](https://user-images.githubusercontent.com/39406635/178779481-1cc21a5b-dc1b-4dcd-9d55-87300096a6a8.jpg)

**Comment by Standard8** [comment]
Thank you for the comments. I think this is probably an issue with the andoird gmail app and/or Thunderbird, rather than Conversations itself. Conversations' display of messages depends on Thunderbird detecting the threads correctly, it uses Thunderbird's global database, which I thought added a bit more threading detection - but that might not be catching this case.

It may be interesting to view the source of the various emails and check out the references headers - it may be that your android client is not setting the references correctly.

In any case, I think this issue is with the android app or Thunderbird. You could file a bug at https://bugzilla.mozilla.org/ and see if they can help. Including details of an example thread with the message ids and references headers might help determine the issue.
