### ISSUE TITLE
Several issues about an Add-on “Thunderbird Conversations”

### ISSUE THREAD

**Issue by ReiNarumiya** [thunderbird-conversations/thunderbird-conversations#1873]
Hi! My name is Rei Narumiya and I love your Thunderbird add-on.

1. I found that "Darko" does not work when "Thunderbird Conversations" is enabled.  I have also contacted the author of the other party. I would be very happy if the two could be used at the same time.

2. The window that appears when you mouse over the sender is strange.
If you use the dark mode theme, the image will look like the one below.
Even if you use some dark mode themes, the phenomenon in the image below will be reproduced.

![Snap2043](https://user-images.githubusercontent.com/105433711/179871501-cc58d863-b626-44d8-977d-05ee82939992.jpg)

3. As you may know, the "Thunderbird Contacts" add-on has been removed by the author. I will report that as well.

I would appreciate it if you could fix the add-on so that it can be used with TB102.0.2 (64-bit)  JPN.

Thank you for creating a great add-on that is extremely versatile.

**Comment by Standard8** [comment]
1. Integration with other add-ons is #1609. It is difficult due to how Conversations works, and I don't yet have a way forward.
2. That's just been fixed in #1883
3. I don't know what the "Thunderbird Contacts" add-on is, whether or not that exists or the state of it is not relevant to Conversations.
