### ISSUE TITLE
"Grouped by Sort" hangs TB, when TB Conversations is active 

### ISSUE THREAD

**Issue by lockerbleiben** [thunderbird-conversations/thunderbird-conversations#1925]
Hey,

I got an error, when using Conversations and grouping messages.

Steps to reproduce:

Sort Messages by Date Descending and activate "Grouped by sort" (see attachment)

Actual results:

When clicking on the grouped row, ALL Messages will be listet in the message area.
When there are lot of messages, TB beginn to hang/freeze (not crashing).

This also happens, when u delete messages from a row above and than the row with lot of messages will get to focus.

Expected results:

Maybe, TB should stop, listing all messages above 100?
At least TB should stop, listing ALL messages, because it will hash at higher message numbers.
(This is the behaviour, when not using Conversations)

Also have a look at https://bugzilla.mozilla.org/show_bug.cgi?id=1799371

![2022 11 07_00h34m23s_001_](https://user-images.githubusercontent.com/4176080/200251656-115f79a3-9c75-4d57-95aa-afccbbde99e1.png)

**Comment by Standard8** [comment]
So although the hang is sort-of Conversation's fault, it turns out that Thunderbird is actually doing something wrong here as well. If Conversations is disabled, then Thunderbird will indicate that the [selected group is only a single conversation, rather than multiple](https://bugzilla.mozilla.org/show_bug.cgi?id=1801558).

I suspect I can work around this in Conversation's message selection handling though. Will have to think about it a bit.

**Comment by Standard8** [comment]
I've found an improvement - we now hand off to Thunderbird's multi-message display (which has its own limits).

Unfortunately Thunderbird might think there's only one conversation when there are multiple, but that's for Thunderbird to fix.

**Comment by lockerbleiben** [comment]
Hey, thx man!
Do i have to do something or are you in contact with the tb team?

**Comment by Standard8** [comment]
I've filed the bug so it is reported with them. You can find that here: https://bugzilla.mozilla.org/show_bug.cgi?id=1801558
