### ISSUE TITLE
No searchable documentation for user wanting to add an attachment

### ISSUE THREAD

**Issue by stephan-dev** [thunderbird-conversations/thunderbird-conversations#1953]
Conversations : `1.0.4`  
Thunderbird : `102.7.1`  
Linux Mint 19 Cinnamon (aka Ubuntu 18.04)  
My only other addon is `Full Address Column` (I tried disabling it)  

Hey, I've had a fit of anger because I had an **attachment** to send to a business contact, the main thing was to produce that attachment (my job), I was late, and when work was done, I couldn't find out how to send an attachment in Thunderbird (Conversations). I furiously googled, because answer was nowhere to be found.
Then I looked myself in the mirror, _it's a free program and free extension, how can I contriboot ?_  

I went on a wrong track because a webpage in french said I should find, somewhere, a button called "continue with editor". This button was nowhere to be found on my screen.  
![image](https://user-images.githubusercontent.com/43588516/220679767-8ad97568-6dd4-4465-8d18-8be637a73c3c.png)  
(arrow and red underline added by me)  
https://fr.flossmanuals.net/thunderbird-1/conversations/  

I do not have this button. **Is this a bug ?**, or was it **removed ?** In the quick reply at the bottom of the conversation, I have two buttons : left of screen : `cancel`. Right : `send`. (actually in french)  
And also on the right : `transfer conversation` + `print conversation`  

Another track (I was in big hurry) was I slowly understood that it was actually NOT possible _at all_ to send an attachment from inside the conversation tab (I had searched in all the Thunderbird menus).
I saw in Conversation options that I had ticked "enable composition tab (experimental)". I thought I was on the right path : leave the conversations view, and reach a full editor.  
To trigger this, one has to do : `ctrl shift + N`.  
But this only opened a new window `quick compose` : a completely blank email (only "from" field is not empty and correct), with a strange code in URL bar : `moz-extension://c7551110-1e7f-46f7-a337-63a06303bf90/compose/compose.html?identityId=id1` (with still no "attach" option)  
I tried to untick that experimental option, to no avail (didn't fix attachment problem).   

Violent googling proved useless (I was hoping to find a screen capture, maybe a video showing where was that `continue with editor` button.  (I had not seen that the french website itself featured a screen capture of the button)
I thought maybe disabling the extension "Conversations" would help, but I didn't want to lose my work (email written in the quick reply down the Conversation, there was just an attachement to add... so close...)  
(I also tried, much later while "debugging", to drag and drop my attachment on the Quick Reply field down the conversation. Doesn't work either, only creates the text of a local link `file:///`.  

Finally I understood that there was a simple way to "bypass" the Conversation extension, while not leaving that tab, and this is what I hope will become googlable : `Ctrl+X (cut) the body of your unsent quick reply and forget that quick reply, you won't use it this time. Click one of the "reply buttons" above in the conversation (the only one to avoid is the one in the middle at the bottom of the page) and this will open a new window, with a full-featured editor, and the From: ; To: ; and Object fields already correct. To add an attachment, find in the tools header the button "📎attach" (joindre🇫🇷)", on the right of the toolbar`  

So my suggestion is to enrich the wiki with a special page that may be titled : "How to add an attachment?", or add this to the FAQ. But first, I need to know if the absence of a `continue using editor` button is a bug on my setting, or if it's normal.  

# steps to reproduce :    
- take an existing conversation, two people is enough
- at some point in the conversation, write a reply with the "reply" button in the middle at the bottom of the thread, which opens the quick reply
- look for a `attach` button..... or a `clip` icon...... or a `attach` _menu item_ in a `insert` or `message` menu
- google for `"thunderbird" "Conversations" how to add an "attachment" ?`

# expected
- user, with a bit of patience, can guess from UI/UX what to do,
- or at least can google for a solution (at least in text version, if not in screenshot or video)

# what happened
- user panics, and loses the €1m deal to the competition, swears to never use Conversations or Thunderbird again, buys a MacBook in mad fit of rage.

**Comment by Standard8** [comment]
Continue using editor is a piece of functionality that was lost when I had to rewrite the compose editor recently and I'd forgotten about re-adding it back. I've [filed this issue for it](https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1955).

Similarly, we did used to have attachments in Conversation's compose editor and [that's also something that hasn't been re-added](https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1956), though this is the first time it has actually been noted since then.

Conversations' does not block Thunderbird's standard compose facilities. On the toolbar there is a write button:

<img width="596" alt="Screenshot 2023-02-23 at 09 55 30" src="https://user-images.githubusercontent.com/520844/220874489-260cb23f-78ff-4828-bf88-15d68479ee52.png">

and each message on Conversation's display has an "automatic" reply button as well as the menu for reply/reply to all/etc:

<img width="217" alt="Screenshot 2023-02-23 at 09 56 31" src="https://user-images.githubusercontent.com/520844/220874768-3edeeb06-50d6-45de-9c1e-2fc21fd1501f.png">

You can also access the reply options via the Message menu for the currently selected message.

All of those have the fully-featured Thunderbird compose window with attachments and more.

I'm going to close this as I've filed separate issues for the parts that are missing.

**Comment by stephan-dev** [comment]
Hi, thanks for explaining, temporary problem, you're working on it.  

> (snipped)

- For the record, on my config, I just tried to `select` a message in a _Conversations_ tab (doesn't seem to select anything). In menu Message, `reply` is still greyed out. But you probably meant selecting a message in a conversation in the _inbox_ tab.
- Thanks for the screenshots! I thought I didn't have that `Write` button, but same thing as above, it **is** present, but only in a normal, non-_Conversations_ tab (where indeed one can `reply`, `to all` in conversation, or `to sender`).

> and each message on Conversation's display has an "automatic" reply button as well as the menu for reply/reply to all/etc

Yes! That's what I said I thought could go in documentation / attachments, but now I understand it's temporary.  
Thanks for this essential plugin, Thunderbird couldn't feel modern without it.
