### ISSUE TITLE
Does not respect "automatically mark as read on display"

### ISSUE THREAD

**Issue by EdwinBerlin** [thunderbird-conversations/thunderbird-conversations#2031]
An issue that was previously fixed has shown up again.  See issue #1282:
https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1281

This problem appeared after an upgrade to version 115.3.2 (64-bit)

Description

I have a bunch of unread emails in Inbox. I go through them one by one with arrows key, reviewing the content in the preview section. I expect the messages to be immediately marked as read, but this doesn't happen.

In fact, the result is inconsistent, sometimes an email is marked as read after 2-3 seconds, sometimes it is not marked as read at all.

**Comment by EdwinBerlin** [comment]
I am running Windows 10 64 bit

**Comment by unlike777** [comment]
same problem

**Comment by dany-on-demand** [comment]
> In fact, the result is inconsistent, sometimes an email is marked as read after 2-3 seconds, sometimes it is not marked as read at all.

The issue is that it's only considered "displayed" as soon as all the images load. You can see that with an experiment:

1. Mark an e-mail with lots of images as unread. 
2. Block loading of images (globally or on that domain/whatever)
3. Clear cache, reload TB, click on e-mail
4. The mail is marked "read" nearly instantly
5. Unblock loading of images
6. Clear cache, reload TB, click on e-mail
7. The mail is marked "read" only after images load

**Comment by Standard8** [comment]
Hmm, given the previous comment, can everyone try this in 115.5.2, looks like it was probably a Thunderbird issue.
