### ISSUE TITLE
Option to configure message reading pane padding and hide the reply button

### ISSUE THREAD

**Issue by jerinphilip** [thunderbird-conversations/thunderbird-conversations#2047]
* **Thunderbird version:** 115.4.1 (64-bit)
* **Thunderbird Conversation version:** 4.1.5
* **Operating System:** ArchLinux

The extension comes with a GMail Mobile like UI for threaded conversations. Thanks for building this, I'm trying to get to use this ahead.

I'd wish the following to be defaults, but since this is subjective, would it be possible to provide options to:

1. Increase the padding for the message window. I'm talking about the window below, where the distance from the borders to text could be configured to be bigger. <br/> <img src="https://github.com/thunderbird-conversations/thunderbird-conversations/assets/727292/3d52c1b1-80b0-44c0-afda-3dd3a9918bd3">

2. Remove the large reply button and the forward/print options links at the end. The forward and reply options are available as buttons, but additionally appear as a large button and links. <br/> <img src="https://github.com/thunderbird-conversations/thunderbird-conversations/assets/727292/84e2669d-2622-41da-b4b4-19aaf21da833">

**Comment by Standard8** [comment]
1. Space tends to be at a premium, so I don't think I would increase the borders unless there's a really good reason. I also wouldn't provide an option for it - that adds complexity, and isn't something I'd want to support here.

2. The "large reply buttons" are different to the separate buttons. They allow access to the quick reply UI, rather than the full compose UI. Some people prefer the quick reply UI. If you don't want that, you can turn it off in the add-on's settings.

The "forward" button is also different to "forward this conversation", in that it only forwards a single message, rather than the whole conversation. Some people do use it, so I won't be changing that.
