### ISSUE TITLE
Request: Option to keep Thunderbird default behavior in compose pane

### ISSUE THREAD

**Issue by jdfoote** [thunderbird-conversations/thunderbird-conversations#2063]
Thanks for the great extension!

I am mostly interested in this extension as a way to thread my messages, and in particular to put my sent messages inline with messages in my inbox, etc.

I actually like some of the features of Thunderbird that the extension removes, and I'm wondering if there's a way to make them optional. In particular, I think that the buttons (and particularly the more button) in the compose window are helpful (see image).

![image](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/452218/8707a7cc-d29a-4eea-84fc-6a93bb8bbec3)

In addition, default Thunderbird, the compose window also has a right-click window with some useful features (like converting some text to an event). 

Is it possible to stop `thunderbird-conversations`  from modifying the compose window?

* **Thunderbird version:** 115.5.0
* **Thunderbird Conversation version:** 4.1.5
* **Operating System:** Ubuntu 23.10

**What did you do?** Tried to right-click to convert text to an event

**What did you expect to happen?** See the right-click menu

**What actually happened?** A menu that only has "select all"

**Comment by Standard8** [comment]
I think you generally mean the message pane rather than the compose window/pane.

Conversations changes the UI to optimise it for displaying multiple messages in the message pane. Without those changes, it would be too busy and take up too much space.

Note that most of the options can also be accessed in multiple ways, e.g. via shortcut keys, or via the context menu on the messages in the message list.

I think "Convert To" is about the only useful option that might be worth adding so that it can be accessed more easily, so I'd be happy for a specific request to be filed for that.
