### ISSUE TITLE
Addon breaks Header Tools Addon

### ISSUE THREAD

**Issue by godzfire** [thunderbird-conversations/thunderbird-conversations#2104]
Thunderbird version: 115.9
Thunderbird Conversation version: 4.1.7
Operating System: Mac OS 12.7.4

I have been using an addon called HeaderTools (either Light or Improved) to regularly modify email header information. It has always normally worked. However installing TB Conversations breaks the addon.

See the pictures below, that is what normally happens when you select to Change Header Details. If you install TB Convos, that window will not open, it's blocked.
<img width="570" alt="SS 2024-04-30 at 4 38 30 PM" src="https://github.com/thunderbird-conversations/thunderbird-conversations/assets/2067820/10deb3c5-1ea3-4c39-88b5-052fabdd2a86">
<img width="440" alt="SS 2024-04-30 at 4 35 47 PM" src="https://github.com/thunderbird-conversations/thunderbird-conversations/assets/2067820/2c25212a-7b7b-4d81-a78f-a7ea239ce461">

Disabling TB convos immediately allow the addon to function again. It's easily reproducible.

**Comment by Standard8** [comment]
Hi, thank you for the report. It seems both of the add-ons have issues which are resulting from Conversations' use of a different method to display the messages. In technical terms it switches Thunderbird into a multi-message display mode, rather than single message display.

In Header Tools Lite case, the main menu option seems to be keyed to what is displayed in the message pane. Conversations' completely replaces what's in the message pane and so Header Tools Lite is broken here.

In actual fact, you can see that Header Tools Lite is broken for the main menu if you select multiple messages (or a collapsed message thread), and then select the menu option.

For this option, they could check to see which messages are selected in the message list, and if it is a single message, edit that header. This might be slightly confusing in Conversations case since Conversations might be displaying multiple messages. They could potentially an option in the header area of Thunderbird's UI, which Conversations would have to support (this is already covered in #1665).

Whilst I'm here, I'll note that the context menu option also has bugs for Header Tools Lite (even without Conversations installed). It uses the same incorrect assumption that what is displayed in the message pane should be edited. For example, if I have one message selected, and I right-click on another and select the option, then it presents me with the details of the originally selected message, rather than the one I right-click on. All the other options in the menu act on the message you right-click on - that's a fundamental property of context menus.

Header Tools Improved looks like it came from the same source, and unfortunately therefore makes pretty much all the same mistakes.

Hence I'm going to close this as I think both of those add-ons are incorrectly attempting to use what is displayed, rather than what is selected. If they used what is selected, they would most likely work a lot better.

**Comment by Standard8** [comment]
Additionally with both of them, they stop working if you don't have the message pane displayed (another symptom of the same issue).
