### ISSUE TITLE
Autoscroll not working when middle-clicking on message text

### ISSUE THREAD

**Issue by Natanji** [thunderbird-conversations/thunderbird-conversations#291]
I just observed that Autoscroll doesn't work like it does in normal Thunderbird messages. When I right-click inside the message window, the autoscroll-icon appears and I can use the mouse for autoscrolling. With Conversation View, this only works when I right-click on a part outside of the message text area, e.g. below on the attachment area of a mail. In the message text area, there is no reaction. It would be very nice if this could be fixed quickly.

**Comment by frumble** [comment]
This bug is sadly still relevant. No autoscrolling available at all with this add-on, which breaks my mouse workflow.

**Comment by Standard8** [comment]
This is actually a bug in Thunderbird, if you select multiple messages so that the summary view (not the Conversation's one) is displayed, and then try it, then it also doesn't work.

The good news is, I've just managed to fix this for the next version of Thunderbird - Thunderbird 91. It is due out in August.

I'll close this out once that is released.

**Comment by Standard8** [comment]
Thunderbird 91 is now out & is starting to roll out via automatic updates to some users, I believe it is available to all users using the manual update mechanism (via help -> about). If not, then it should be within the next couple of weeks.
